DELETE http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/1
###
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11c2thbjciLCJpZCI6IjY4MzVlNGJlY2I3YzdiZjRlOWFiYzQzYSIsImlhdCI6MTc0OTEyMDk4OX0.zzVMai3NKGHPriyyfRv83bVnU-l6cO0iVQ7A6dtYKOo

{
    "content": "notes creation using token",
    "important": true,
    "userId": "6835e4becb7c7bf4e9abc43a"
}
###
PUT http://localhost:3001/api/notes/6824b1b248af5bdadc88f9d6
content-type: application/json

{
    "content":"sam",
    "important": false
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "muskan7",
    "name": "muskan lama",
    "password": "password123"
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "muskan7",
    "password": "password123"
}
###
POST http://localhost:3001/api/testing/reset
