DELETE http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/1
###
POST http://localhost:3001/api/notes/
content-type: application/json

{
    "content": "sample by muskan",
    "important": true,
    "userId": "6835e4becb7c7bf4e9abc43a"
}
###
PUT http://localhost:3001/api/notes/6824b1b248af5bdadc88f9d6
content-type: application/json

{
    "content":"sam",
    "important": false
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "muskan7",
    "name": "muskan lama",
    "password": "password123"
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "muskan7",
    "password": "password123"
}