POST http://localhost:3001/api/notes
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIgMSIsImlkIjoxLCJpYXQiOjE3NTU3MDYyMjh9.f9gDNHnS-sWr2vsqxwNDZp5gY540-6o0XS_oSSJnciU

{
    "content": "",
    "important": true
}
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "user 4",
    "name": "test user",
    "disabled": true
}
###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    "important": true
}
###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "user 4",
    "password": "secret"
}
###
DELETE http://localhost:3001/api/notes/6
