POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "test note 2",
    "important": false
}
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "testuser",
    "name": "test user"
}
###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    "important": true
}
###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "testuser",
    "password": "secret"
}