POST http://localhost:3001/api/notes
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOjEsImlhdCI6MTc1NDk4NzA3NH0.hvbneJDzyul7J3GXqvfk4TWaLyZ_qFxuFc2CEefbivA

{
    "content": "hello",
    "important": false
}
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "testuser",
    "name": "test user"
}
###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    "important": true
}
###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "testuser",
    "password": "secret"
}
###
DELETE http://localhost:3001/api/notes/6
